### ISSUE TITLE
Error running toy example

### ISSUE THREAD

**Issue by celianeto** [moiexpositoalonsolab/grenepipe#30] opened 2022-12-16 12:31 UTC
Hi!

I'm trying to set up and run grenepipe but I'm running into some troubles when I play with the toy example. Please see below the screenshot of the error:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/66737212/208097899-cf5f3d48-bb8e-4520-9cf2-015f8385b852.png">

As I am fairly new to all of this, I apologize in advance if this is just caused by something small I am missing, and appreciate all the help you can provide.

Best,
Célia

**Comment by lczech** [comment] 2022-12-16 18:55
Hi @celianeto,

it looks like you are trying to run grenepipe on a cluster, using the cluster-wide version of conda, right? The error that you are seeing is likely caused by some issue with that installation of conda, or lacking user rights to install certain packages.

There are two things that you could try:

 1. Reach out to the cluster IT admins, and ask them about it. This issue is something that you as a user of the cluster likely cannot fix yourself, unfortunately, as it will need changes on the system level.
 2. Use your own conda installation. See for example the grenepipe wiki [here](https://github.com/moiexpositoalonsolab/grenepipe/wiki/Setup-and-Usage#prerequisites) to set up conda and mamba for your own user. You can set that up in the home directory on the cluster, and hence should not run into these user rights issues.

Hope that helps, so long
Lucas

**Comment by lczech** [comment] 2023-01-21 01:04
Hi @celianeto, any updates on this?

**Comment by celianeto** [comment] 2023-01-22 08:34
Hi @lczech ! I managed to run it in a different cluster. However, now I'm running into a different problem. 

[E::bgzf_close] File write failed
samtools sort: failed to create temporary file "/tmp/tmp_568zwvv/samtools.5795.2397.tmp.0008.bam": Input/output error

From the log file when I run bwa mem. I noticed you had some comments about problems with tmp files on your scripts. Could this be it? I have set the path to a tmp-folder in the config file and will try again. 

Thanks,
Célia

**Comment by lczech** [comment] 2023-01-22 11:40
Hi @celianeto,

hm, that error looks again like an issue with the cluster, where the `/tmp` directory might be too full, or similar problems. You can try setting a different directory for samtool to use for its temporary files. In the `config.yaml`, see `params: samtools: temp-dir` for details, and set that to some other directory.

Hope that helps, let me know if that also causes trouble
Lucas

**Comment by lczech** [comment] 2023-03-30 01:24
Hey @celianeto,

any updates? You could try running it locally on your computer, to see if that works. Also, you could try with the more recent grenepipe v0.12.0, which fixes a few related issues, maybe that helps!

Cheers
Lucas

**Comment by lczech** [comment] 2023-04-27 21:44
Hey @celianeto,

seems this issue is no longer active. Going to close it for now, but feel free to re-open or start a new one should you still be working on this!

Cheers
Lucas

**Closed by lczech** 2023-04-27 21:44 UTC
